### ISSUE TITLE
Couldn't run linux mint mate 

### ISSUE THREAD

**Issue by iamhbc** [Azure/azure-linux-extensions#1620]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-linux-extensions/pull/1769
- [ ] https://github.com/Azure/azure-linux-extensions/pull/1767
- [ ] https://github.com/Azure/azure-linux-extensions/pull/1766
```

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-linux-extensions/pull/1760
- [ ] https://github.com/Azure/azure-linux-extensions/pull/1770
- [ ] https://github.com/Azure/azure-linux-extensions/pull/1765
- [ ] https://github.com/Azure/azure-linux-extensions/issues/1764
```
